FROM python:3.10-slim
WORKDIR /app
# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .
CMD ["python", "app.py"]