
services:
  - type: web
    name: api-gateway
    env: docker
    plan: free
    contextPath: deployment/backend/api_gateway
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: content-engine
    env: docker
    plan: free
    contextPath: deployment/backend/content_engine
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: learner-data-tracker
    env: docker
    plan: free
    contextPath: deployment/backend/learner_data_tracker
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: personalisation-engine
    env: docker
    plan: free
    contextPath: deployment/backend/personalisation_engine
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: adaptive-learning-ui
    env: docker
    plan: free
    contextPath: deployment/frontend
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /
