
version: "3.8"

services:
  api_gateway:
    build: /Users/oawujo/AdaptiveLearningPlatformFinal/backend/api_gateway
    ports:
      - "8000:8000"
    env_file:
      - /Users/oawujo/AdaptiveLearningPlatformFinal/deployment/docker/.env

  learner_data_tracker:
    build: /Users/oawujo/AdaptiveLearningPlatformFinal/backend/learner_data_tracker
    ports:
      - "8001:8001"
    env_file:
      - /Users/oawujo/AdaptiveLearningPlatformFinal/deployment/docker/.env

  personalisation_engine:
    build: /Users/oawujo/AdaptiveLearningPlatformFinal/backend/personalisation_engine
    ports:
      - "8002:8002"
    env_file:
      - /Users/oawujo/AdaptiveLearningPlatformFinal/deployment/docker/.env

  content_engine:
    build: /Users/oawujo/AdaptiveLearningPlatformFinal/backend/content_engine
    ports:
      - "8003:8003"
    env_file:
      - /Users/oawujo/AdaptiveLearningPlatformFinal/deployment/docker/.env

  frontend:
    build:
      context: /Users/oawujo/AdaptiveLearningPlatformFinal/frontend
      dockerfile: /Users/oawujo/AdaptiveLearningPlatformFinal/deployment/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
